initial commit
Igor-Tukh/java pull request #1
Opened 2017-09-12 13:11 UTC by Igor-Tukh

2017-09-24 07:59 UTC, yurii-litvinov requested changes

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +    private List[] ht;
Лучше не сокращать имена полей, потому как написать их надо всего один раз, а читать --- много, и каждый раз догадываться, что имел в виду автор, может быть слишком трудоёмко. Лучше `private List[] hashTable`

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +            ht[i] = new List();
Лучше заключать тело в фигурные скобки даже если там один оператор, во избежание ошибок типа
```java
for (int i = 0; i < mod; i++)
    System.out.println(i);
    ht[i] = new List();
```

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +        ht = new List[mod];
Если в хеш-таблице будет храниться всего пара значений, это не очень эффективно использует память. А если миллионы значений, то будет много коллизий и хеш-таблица будет работать медленно. Лучше делать, как обычно делают --- увеличивать вдвое размер хеш-таблицы, когда в ней становится слишком много значений, а начинать с какого-нибудь маленького размера

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +     * @return (int) number of keys in hash-table.
Тип возвращаемого значения и так понятен из сигнатуры метода, которая и в документации тоже будет

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +        return ht[getHash(key)].contains(key);
getHash, кажется, может вернуть отрицательное число при арифметическом переполнении

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/HashTable/HashTable.java
> +
Две пустые строки подряд обычно не ставятся

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/List/List.java
> +        tail = null;
Эти поля и так проинициализируются значениями по умолчанию, это ведь не C++ :)

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/List/List.java
> +
Перед `}` пустые строки вообще обычно не ставятся

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/List/List.java
> +    private class ListNode {
Ещё надо `static`, иначе ListNode будет содержать в себе ссылку на объект объемлющего класса. Так уж устроены вложенные классы в Java

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/List/List.java
> +        private ListNode next, prev;
Лучше объявлять каждое поле отдельно, иначе их несколько сложнее найти глазами

2017-09-24 07:59 UTC, yurii-litvinov commented on hw01/src/ru/spbau/mit/tukh/hw01/List/List.java
> +        ListNode(String _key, String _value) {
Параметры показываются во всплывающих подсказках каждый раз, когда кто-то вызывает конструктор, поэтому должны называться "по-человечески", без всяких подчёркиваний.

2017-09-26 19:54 UTC, Igor-Tukh commented
Замечания поправил.
Мне кажется, что getHash все-таки не должен был возвращать отрицательные значения из-за аккуратных кастов, но теперь, он, как мне кажется, точно не будет этого делать.

2017-11-13 22:24 UTC, merged