hw08: initial commit, all methods implemented
Igor-Tukh/java pull request #9
Opened 2017-11-07 23:00 UTC by Igor-Tukh

2017-12-04 18:29 UTC, yurii-litvinov requested changes
Надо ещё gradle-wrapper.jar, иначе из консоли не собирается.

2017-12-04 18:29 UTC, yurii-litvinov commented on hw08/src/main/java/ru/spbau/mit/tukh/hw08/Function/Function1/Function1.java
> +public interface Function1<T, R> {
Есть ещё аннотация `@FunctionalInterface`, которая говорит компилятору проверить, что реально функциональный интерфейс получился

2017-12-04 18:29 UTC, yurii-litvinov commented on hw08/src/main/java/ru/spbau/mit/tukh/hw08/Function/Predicate/Predicate.java
> +    static Predicate ALWAYS_TRUE() {
Это метод, так что лучше и называть его как метод. И добавить ему параметр-тип, а то возвращается сырой предикат.

2017-12-04 18:29 UTC, yurii-litvinov commented on hw08/src/main/java/ru/spbau/mit/tukh/hw08/Collections/Collections.java
> +package ru.spbau.mit.tukh.hw08.Collections;
Делать каждый класс в своём собственном пакете не очень удобно, да и особо незачем. Пакеты же средства группировки классов.

2017-12-04 18:40 UTC, Igor-Tukh commented
А Вы можете пока, пожалуйста, ничего больше у меня не проверять до среды (06.12)?
Я бы перепроверил содержимое репозитория (понимаю, что делайн был указан и прошел, но после первого минуса сверху просто физически не успел совершить ревизию, и это очень грустно).

2017-12-04 18:53 UTC, yurii-litvinov commented
Да, я после FP приостановлю пока проверку, а то придётся снимать баллы за одни и те же ошибки (всё равно до среды я только и успею FP допроверять). Хотя просил же на паре посмотреть на старые задачи и поправить :)

2017-12-11 17:28 UTC, yurii-litvinov approved these changes
👍

2018-01-01 20:28 UTC, merged